her2:
  sequence: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  mutations:
    - "A1A"
    - "A2A"
  known_positions: [1, 2]

rfah:
  sequence: "MSEQHAQGADAVVDDSSRPNDPEPKRAREQHHHHHH"
  mutations:
    - "M1A"
    - "M2A"
  known_positions: [142, 144, 146]
  frustra_positions: [142, 144, 146]

i89:
  sequence: "GSHMASMEDLQAEARAFLSEEMIAEFKAAFDMFDADGGGDISYKAVGTVFRMLGINPSKEVLDYLKEKIDVDGSGTIDFEEFLVLMVYIMKQDA"
  mutations:
    - "I81S"
  known_positions: [89]
  frustra_positions: [89] 