[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alphamask"
version = "0.1.0"
description = "TBD"
readme = "README.md"
authors = [
    {name = "Felipe Engelberger", email = "felipeengelberger@gmail.com"},
]
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "biopython>=1.84",
    "igraph>=0.11.8",
    "leidenalg>=0.10.2",
    "kaleido==0.2.1",
    "numpy>=2.1.3",
    "texttable>=1.7.0",
]

[project.urls]
Homepage = "https://github.com/engelberger/alphamask"
Repository = "https://github.com/engelberger/alphamask"

[tool.setuptools]
packages = ["alphamask"]

[tool.setuptools.package-data]
alphamask = ["py.typed"] 