[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "alphamask"
version = "0.1.1"
description = "TBD"
readme = "README.md"
authors = [
    {name = "Felipe Engelberger", email = "felipeengelberger@gmail.com"},
]
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=1.23,<2.0",
    "cudf-cu12>=24.4.0",
    "numba>=0.57,<0.61",
    "jax==0.5.1",
    "ipython",
    "plotly==5.24.1",
    "pyyaml",
    "pathlib",
    "jsonschema",
    "typing-extensions>=4.12.0"
]

[project.urls]
Homepage = "https://github.com/engelberger/alphamask"
Repository = "https://github.com/engelberger/alphamask"

[tool.setuptools]
packages = ["alphamask", "alphamask.cli"]

[tool.setuptools.package-data]
alphamask = [
    "py.typed",
    "config/*.yaml",
    "config/*.json",
    "docs/*.md"
]

[project.scripts]
alphamask = "alphamask.cli.main:main"